### PR TITLE
add Dustin's link

### PR DESCRIPTION
**Pull request by Dantexkilljoy**

### CODE REVIEW

**Review by johnLeavell — APPROVED** [review]
👍🏾

**Review by Nancy-techprep — COMMENTED** [review]
dustin's link has been added and moved

**Review by camille-arce — APPROVED** [review]
good!

**Review by ryanmertz3 — APPROVED** [review]

**Review by Nancy-techprep — APPROVED** [review]

**Comment by Dantexkilljoy** [comment]
lets go big ian!!

**Pull request merged**
